name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
    tags-ignore:
      - '**'

jobs:
  release:
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yml@v1
    with:
      files: build/Hi
    secrets: inherit

  docs_publish:
    needs:
      - release
    uses: jeffersonlab/java-workflows/.github/workflows/gh-pages-publish.yml@v1
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit
