name: GitHub Pages Publish

on:
  workflow_call:
    inputs:
      semvertag:
        required: true
        type: string
      folder:
        required: false
        type: string
        default: 'build/docs/javadoc'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Gradle doc tasks
        run: ./gradlew javadoc
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ inputs.folder }}
          target-folder: ${{ inputs.semvertag }}