name: GitHub Release

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
      files:
        required: false
        type: string
    outputs:
      semvertag:
        description: "The semantic versioning tag name created ('v' prefix)"
        value: ${{ jobs.release.outputs.semvertag }}
      semver:
        description: "The semantic versioning name created (no prefix)"
        value: ${{ jobs.release.outputs.semver }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      semvertag: ${{ steps.getver.outputs.semvertag }}
      semver: ${{ steps.getver.outputs.semver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: Read version file
        id: getver
        run: |
          VER=$(cat VERSION)
          echo "VERSION=v$VER" >> $GITHUB_ENV
          echo "semvertag=v$VER" >> $GITHUB_OUTPUT
          echo "semver=$VER" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.VERSION }}
          files: ${{ inputs.files }}