name: Maven Central Publish

on:
  workflow_call:
    java-version:
      required: false
      type: string
      default: '21'
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY:
        required: true
      SIGNING_PASSWORD:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: artifact
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername : ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword : ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_PASSWORD }}